# Generated by Django 3.0.2 on 2020-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20200509_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('nothing', '---'), ('Mass', (('kilogram', 'kilogram'), ('gram', 'gram'))), ('Volume', (('liter', 'liter'), ('mililiter', 'mililiter')))], max_length=40),
        ),
    ]
