# Generated by Django 3.0.2 on 2020-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('ingr', models.CharField(max_length=50)),
                ('check', models.BooleanField(default=True)),
            ],
        ),
    ]
