# Generated by Django 3.0.2 on 2020-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Servings',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Thumbnail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Title_link',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipes_view',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Recipe',
            field=models.CharField(max_length=150),
        ),
    ]
