# Generated by Django 3.0.2 on 2020-01-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200120_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Title_link',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
