# Generated by Django 3.0.2 on 2020-01-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200121_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=40)),
                ('rating', models.IntegerField(null=True)),
                ('orating', models.IntegerField(null=True)),
                ('review', models.TextField(null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
