# Generated by Django 3.0.2 on 2020-01-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200131_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='orating',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
