# Generated by Django 3.0.2 on 2020-01-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200131_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
