# Generated by Django 3.0.2 on 2020-02-10 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200131_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
