# Generated by Django 3.0.2 on 2020-04-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20200422_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipe_id',
            field=models.BigIntegerField(),
        ),
    ]
