# Generated by Django 3.0.2 on 2020-04-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20200422_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
