# Generated by Django 3.0.2 on 2020-04-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20200422_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='recipe_id',
            new_name='recipeid',
        ),
    ]
