# Generated by Django 3.0.2 on 2020-04-22 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20200422_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='recipeid',
            new_name='recipe',
        ),
    ]
