# Generated by Django 3.0.2 on 2020-04-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20200422_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ext',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='qty',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.TextField(null=True),
        ),
    ]
